# pyinstaller.spec
# 使用方式：pyinstaller pyinstaller.spec

import sys
from pathlib import Path

ROOT = Path(SPECPATH)

a = Analysis(
    ['backend/main.py'],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / 'frontend'), 'frontend'),
        (str(ROOT / 'docs'), 'docs'),
        (str(ROOT / 'backend' / 'webview2'), 'webview2'), # 要注意不能写成 backend/webview2
    ],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'pydantic',
        'pydantic.deprecated',
        'pydantic.deprecated.copy_internals',
        'webview',
        'webview.platforms',
        'webview.platforms.edgechromium',
        'backend',
        'backend.server',
        'backend.window',
        'backend.tray',
        'backend.qmt_client',
        'backend.signal_handler',
        'backend.strategy_manager',
        'backend.utils',
        'backend.logger',
        'backend.constants',
        'backend.qmt_xtconstant',
        'backend.mock_xtquant',
        'config',
        'config.settings',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'jedi',
        'IPython',
        'sqlalchemy',
        'psycopg2',
        'mysql',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='QMT-Live-Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon=str(ROOT / 'assets' / 'icon.ico') if (ROOT / 'assets' / 'icon.ico').exists() else None,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
